version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - backend

  redis:
    image: redis:7
    container_name: redis
    expose:
      - "6379"
    networks:
      - backend

  backend:
    build: .
    container_name: sku-course-backend
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    expose:
      - "8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    networks:
      - backend

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    depends_on:
      - backend
    networks:
      - backend

#  certbot:
#    image: certbot/certbot
#    container_name: certbot
#    volumes:
#      - ./nginx/certbot/conf:/etc/letsencrypt
#      - ./nginx/certbot/www:/var/www/certbot
#    entrypoint: ""

volumes:
  mysql-data:

networks:
  backend: