server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydatabase?useSSL=false&serverTimezone=Asia/Seoul
    username: yeseob
    password: kablose12!!

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

lecture:
  operation:
    start-hour: 0
    end-hour: 24
    start-minute: 60

cors:
  allowed-origins:
    - http://localhost:5173