spring:
  profiles:
    default: dev
  jackson:
    time-zone: Asia/Seoul

jwt:
  secret: "MzJieXRlc2VjcmV0a2V5MTIzNDU2Nzg5MDEyMzQ1Njc4OTA="

springdoc:
  override-with-generic-response: false

enrollment:
  max-courses: 10

queue:
  key: "enrollment:queue"
