
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/sku_course?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: kablose12!!

  data:
    redis:
      host: redis
      port: 6379

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

lecture:
  operation:
    start-hour: 8
    end-hour: 22


cors:
  allowed-origins:
    - https://skusimulator.com
    - https://www.skusimulator.com
    - https://skusimulator.netlify.app